# https://dbx.readthedocs.io/en/latest/reference/deployment/

custom:
  git-source-default: &git-source-default
    git_source:
      git_url: "https://github.com/thisisthemurph/dbx-demo.git"
      git_provider: "GitHub"
      git_branch: "main"

  default-cluster-information: &default-cluster-information
    existing_cluster_id: "0620-125415-q7klmhol"

build:
  no_build: true

environments:
  default:
    workflows:
      - name: "demo-basic"
        tasks:
          - task_key: "wf2-t1"
            <<: *default-cluster-information
            spark_python_task:
              python_file: "file://src/test_project/tasks/dbx-demo-job.py"

      - name: "demo-scheduled-workflow"
        <<: *git-source-default
        schedule:
          quartz_cron_expression: "7 0/5 * * * ?"
          timezone_id: "UTC"
          pause_status: "UNPAUSED"
        max_concurrent_runs: 1
        tasks:
          - task_key: "wf2-t1"
            existing_cluster_id: "0620-125415-q7klmhol"
            spark_python_task: 
              source: "GIT"
              python_file: "src/test_project/tasks/dbx-demo-job.py"
      
      - name: "demo-calcs-workflow"
        <<: *git-source-default
        tasks:
          - task_key: "calcs_make-data"
            <<: *default-cluster-information
            spark_python_task:
              source: "GIT"
              python_file: "src/calcs_project/tasks/make_data.py"

          - task_key: "calcs_calculate-average-temperature"
            <<: *default-cluster-information
            depends_on:
              - task_key: "calcs_make-data"
            spark_python_task:
              source: "GIT"
              python_file: "src/calcs_project/tasks/calculate_average_temperature.py"
