custom:
  git-source-default: &git-source-default
    git_source:
      git_url: "https://github.com/thisisthemurph/dbx-demo.git"
      git_provider: "GitHub"
      git_branch: "main"

build:
  no_build: true

environments:
  default:
    workflows:
      - name: "workflow-1"
        <<: *git-source-default
        tasks:
          - task_key: "wf2-t1"
            existing_cluster_id: "0620-125415-q7klmhol"
            spark_python_task: 
              source: "GIT"
              python_file: "src/test_project/tasks/dbx-demo-job.py"
      
      - name: "demo-calcs-workflow"
        <<: *git-source-default
        tasks:
          - task_key: "calcs_make-data"
            existing_cluster_id: "0620-125415-q7klmhol"
            spark_python_task:
              source: "GIT"
              python_file: "src/calcs_project/tasks/make_data.py"

          - task_key: "calcs_calculate-average-temperature"
            depends_on:
              - task_key: "calcs_make-data"
            existing_cluster_id: "0620-125415-q7klmhol"
            spark_python_task:
              source: "GIT"
              python_file: "src/calcs_project/tasks/calculate_average_temperature.py"
